[package]
name = "res_reader"
version = "0.1.0"
description = "MAX resource reader"
authors = ["Aneta Suns"]
edition = "2024"
license = "MIT"

[dependencies]
log = "0.4.27"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
